export const movieTitles: string[] = [
  "The Godfather",
  "The Dark Knight",
  "Pulp Fiction",
  "Forrest Gump",
  "The Shawshank Redemption",
  "Inception",
  "Fight Club",
  "The Matrix",
  "Titanic",
  "Interstellar",
  "The Prestige",
  "Gladiator",
  "Saving Private Ryan",
  "The Green Mile",
  "Schindler's List",
  "The Silence of the Lambs",
  "Braveheart",
  "The Departed",
  "Whiplash",
  "Good Will Hunting",
  "The Social Network",
  "Joker",
  "Parasite",
  "Deadpool",
  "Logan",
  "The Wolf of Wall Street",
  "Shutter Island",
  "Catch Me If You Can",
  "Django Unchained",
  "Inglourious Basterds",
  "The Hateful Eight",
  "No Country for Old Men",
  "There Will Be Blood",
  "The Revenant",
  "Birdman",
  "La La Land",
  "Her",
  "Eternal Sunshine of the Spotless Mind",
  "The Grand Budapest Hotel",
  "Moonlight",
  "Arrival",
  "Blade Runner 2049",
  "Mad Max: Fury Road",
  "The Irishman",
  "Marriage Story",
  "The Big Short",
  "A Beautiful Mind",
  "Cast Away",
  "The Truman Show",
  "American Beauty",
  "The Sixth Sense",
  "The Pianist",
  "Life Is Beautiful",
  "Slumdog Millionaire",
  "The Imitation Game",
  "The Theory of Everything",
  "Bohemian Rhapsody",
  "Rocketman",
  "The King’s Speech",
  "Les Misérables",
  "The Greatest Showman",
  "Moulin Rouge!",
  "The Lion King",
  "Toy Story",
  "Finding Nemo",
  "Up",
  "Coco",
  "WALL·E",
  "Inside Out",
  "Ratatouille",
  "Frozen",
  "Zootopia",
  "Encanto",
  "How to Train Your Dragon",
  "Kung Fu Panda",
  "Shrek",
  "The Lego Movie",
  "Despicable Me",
  "Minions",
  "Monsters, Inc.",
  "Harry Potter and the Sorcerer’s Stone",
  "Avatar",
  "Star Wars: A New Hope",
  "Rogue One: A Star Wars Story",
  "Wonder Woman",
  "Aquaman",
  "Justice League",
  "Spider-Man: Into the Spider-Verse",
  "Jumanji: Welcome to the Jungle",
  "Jurassic Park",
  "The Hunger Games",
  "Transformers",
  "Pirates of the Caribbean: The Curse of the Black Pearl",
  "Aladdin (2019)",
  "Beauty and the Beast (2017)",
  "Maleficent",
  "The Jungle Book (2016)",
  "Man of Steel",
  "The Suicide Squad",
  "Birds of Prey",
  "It",
  "The Conjuring",
  "Annabelle",
  "Insidious",
  "The Nun",
  "Divergent",
  "Twilight",
  "The Fault in Our Stars",
  "Call Me By Your Name",
  "Lady Bird",
  "Roma",
  "The Shape of Water",
  "Get Out",
  "Us",
  "A Quiet Place",
  "The Lighthouse",
  "Knives Out",
  "Ready Player One",
  "Baby Driver",
  "Spotlight",
  "The Martian",
  "Gravity",
  "Prisoners",
  "Requiem for a Dream",
  "Amélie",
  "Pan's Labyrinth",
  "Oldboy",
  "The Lives of Others",
  "Cinema Paradiso",
  "The Intouchables",
  "Crouching Tiger, Hidden Dragon",
  "Letters from Iwo Jima",
  "Brokeback Mountain",
  "The Last Samurai",
  "The Iron Giant",
  "Coraline",
  "The Secret Life of Walter Mitty",
  "Luca",
  "Turning Red",
  "Soul",
  "Home Alone",
  "Elf",
  "Mean Girls",
  "Clueless",
  "The Princess Diaries",
  "The Parent Trap",
  "Legally Blonde",
  "Freaky Friday",
  "High School Musical",
  "Camp Rock",
  "The Lizzie McGuire Movie",
  "Hannah Montana: The Movie",
  "Pitch Perfect",
  "The Notebook",
  "10 Things I Hate About You",
  "She's the Man",
  "Easy A",
  "To All the Boys I've Loved Before",
  "The Kissing Booth",
  "The Fault in Our Stars",
  "Call Me By Your Name",
  "Lady Bird",
  "The Shape of Water",
  "Get Out",
  "Us",
  "A Quiet Place",
  "Knives Out",
  "Ready Player One",
  "Baby Driver",
  "Spotlight",
  "The Martian",
  "Gravity",
  "Prisoners",
  "Requiem for a Dream",
  "Amélie",
  "Pan's Labyrinth",
  "Oldboy",
  "The Lives of Others",
  "Cinema Paradiso",
  "The Intouchables",
  "Crouching Tiger, Hidden Dragon",
  "Letters from Iwo Jima",
  "Brokeback Mountain",
  "The Last Samurai",
  "The Iron Giant",
  "Coraline",
  "The Secret Life of Walter Mitty",
  "Luca",
  "Turning Red",
  "Soul",
  "Flipped",
  "Bridge to Terabithia",
  "Akeelah and the Bee",
  "The Pursuit of Happyness",
  "Big Fish",
  "Julie & Julia",
  "Chef",
  "Hidden Figures",
  "The Help",
  "Little Miss Sunshine",
  "Inside Man",
  "Catch Me If You Can",
  "Big",
  "Cast Away",
  "The Terminal",
  "Yes Man",
  "Bruce Almighty",
  "Click",
  "The Truman Show",
  "Man on the Moon",
  "The Blind Side",
  "127 Hours",
  "Moneyball",
  "The Soloist",
  "Into the Wild",
  "Wild",
  "The Bucket List",
  "The Secret Garden",
  "Secondhand Lions",
  "Marley & Me",
  "Marcel the Shell with Shoes On",
  "Enchanted",
  "Ella Enchanted",
  "Miss Congeniality",
  "Erin Brockovich",
  "The Intern",
  "The Holiday",
  "Notting Hill",
  "Love Actually",
  "About Time",
  "Begin Again",
  "Yesterday",
  "The Peanut Butter Falcon",
  "The Florida Project",
  "The Way Way Back",
  "Me and Earl and the Dying Girl",
  "The Perks of Being a Wallflower",
  "Paper Towns",
  "The Art of Getting By",
  "The Spectacular Now",
  "The Edge of Seventeen",
  "A Bug's Life",
  "The Good Dinosaur",
  "Monsters University",
  "The Emperor's New Groove",
  "Tangled",
  "Wreck-It Ralph",
  "Onward",
  "Final Destinaion"
];
